apiVersion: v3alpha1
service:
  containers:
    -  name: server
       image: dname:1.0.0
       ports:
         -  containerPort: 8080
  ports:
    -  name: openapi
       port: 80
       protocol: TCP
       targetPort: 8080
  proxy:
    paths:
      -  certified: true
         path: /
         servicePort: 80
