version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      MEM_OPTS: '-Xms256m -Xmx756m -XX:+HeapDumpOnOutOfMemoryError'
    networks:
      supos_default:
        aliases:
        - 605fd270fb5b3563411572db01634214.apps
networks:
   supos_default:
     external: true
