# -------------------------------------------- #
#               容器编排定义                     #
# 此配置文件仅适用于高代码或高低代码混合的APP，不适  #
# 用于纯低代码的APP。                            #
# -------------------------------------------- #
# 安装包版本。必填。固定值。
apiVersion: v3alpha1
# 暴露服务。非必填。
service:
  # 运行副本数；必填。默认为1
  replicas: 1
  # 对外暴露http服务配置。非必填。
  proxy:
    # url路由规则。必填。
    paths:
      # 匹配的uri。必填。
      - path: /api
        # 指向posts.port的配置端口。必填。
        servicePort: 80
  # 服务端口映射配置。必填。
  ports:
    # 服务暴露端口。必填。
    - port: 80
      # 指向POD中的容器端口。必填。取值：containers.ports.containerPort
      targetPort: 8080
      # 通讯协议。必填。一般为TCP
      protocol: TCP
      # 名称。必填。一种标识。英文小写字母。
      # 注意：如果需要将此端口暴露成openapi。则此时，可以将name设置为openapi。
      name: http
  # 初始化容器配置。非必填。
  initContainers:
    - name: init
      image: init:1.0.0
  # 容器配置。必填。
  containers:
    # 容器名称。必填。描述容器的功能，如frontend、backend
    - name: sugar-sms
      # 镜像名称。必填。
      # 当镜像通过build.yaml进行构建的，取值为build.yaml中的<images.name>:<images.tag>。
      # 当镜像不是通过build.yaml构建的，则需要描述全路径名(fullPathName)，如registry.supos.ai/jenkins/demo:1.0.0
      image: registry.supos.ai/library/openjdk:8-jdk-alpine
      # 容器暴露的端口列表。必填。
      ports:
        # 容器在POD中暴露的端口。
        - containerPort: 8080
      # 持久卷挂载。非必填。
      volumeMounts:
        # 卷名称。必填。从requirement.yaml中的volumes.name取值。
        - name: sugar
          # 容器内挂载路径。必填。
          mountPath: /var/sugar
      # 定义CPU、内存资源。必填。当未声明时使用默认值。cpu=10m~1000m，memory=128Mi~512Mi
      resources:
        # 最小申请资源大小。必填。
        requests:
          # cpu时间片大小，以“m”为单位，1000m为一核心。
          cpu: 10m
          # 内存大小。以“Mi”、“Gi”为单位。1024Mi=1Gi。
          memory: 128Mi
        # 最大限制资源大小。必填。
        limits:
          cpu: 1000m
          memory: 512Mi
#    - name: frontend
#      image: frontend:1.0.0
#      ports:
#        - containerPort: 8080
#      resources:
#        requests:
#          cpu: 10m
#          memory: 128Mi
#        limits:
#          cpu: 1000m
#          memory: 128Mi