supos:
  supos-address: http://47.129.0.177:8080
  app-id: 4d4384283dc193f39d6b95b5db1b8940
  app-secret: xxx
  ak: 73101af46504b78d84d3b12fab482777
  sk: 50fdd25963042ace27d3963cbe78c065
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sugar_sms?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
